### PR TITLE
Fix shirt and phone number form validation

### LINKED ISSUE #148: Fix Edit User page for users without t-shirt sizes
Current attempts to edit a user that doesn't have a T-shirt size set fail to load the page. This needs to be fixed so that we can set t-shirt sizes for these users (or ignore the field for system users).

This is High-Priority and should be fixed for the next point release.

### PR DESCRIPTION
**Pull request by msoucy**
Closes #148

### CODE REVIEW

**Comment by jeffaburke** [comment]
@msoucy this still does not solve the duplication of guardians on an incorrect entry of the form correct?

**Comment by jeffaburke** [comment]
also is there any way to make the text for N/A grayed out (not actually there) but when they start typing it disappears? So they do not have to remove the N/A.

**Comment by msoucy** [comment]
~~Correct, it does not solve the guardian issue.~~

Now it does

**Review by jeffaburke — APPROVED** [review]
I like this all good for me

**Pull request merged**
