### PR TITLE
Escape Form Fields

### PR DESCRIPTION
**Pull request by JoeJanickiChSh**
I'm pretty sure WTForms sanitizes inputs for SQL but does not HTML escape them. This just adds filters to the form fields that escape them to be HTML-safe and avoid XSS attacks.

### CODE REVIEW

**Comment by msoucy** [comment]
Sanitizing is all well and good, but if we used wtforms validators we wouldn't need as much sanitization - the form itself would reject invalid characters

**Comment by JoeJanickiChSh** [comment]
> 

I'm pretty sure `<` and `>` characters are allowed in emails (in certain circumstances) and it is possible that a fully valid email address would get rejected by the validator.

**Comment by msoucy** [comment]
In my opinion, that falls under the situation of "play stupid games win stupid prizes" - if you're going to make a pathological email address, don't be surprised when it fails in most websites

**Comment by msoucy** [comment]
@JoeJanickiChSh Once #77 is merged, please rebase your changes and fix the merge conflicts.

**Comment by msoucy** [comment]
OBE

**Pull request closed without merging**
