### PR TITLE
Only show data for the current year

### PR DESCRIPTION
**Pull request by msoucy**
- Events
- Funds
- Hours

### CODE REVIEW

**Comment by msoucy** [comment]
@bot190 thoughts?

**Comment by bot190** [comment]
Yeah sorry haven't had a chance to review this. I'll try to make time in the next week.

**Review by bot190 — APPROVED** [review]
I made a small fix to the postgresql implementation, as well as moved the cutoff to July to better align with the school transition. (Previously BattleCry was being counted towards the new year which is not expected). 

I'm approving, but want @msoucy to take a quick look at the change I made before merging.

**Comment by msoucy** [comment]
The deed is done

**Pull request merged**
